# Importing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# get data

In [4]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication',header=None)
data.columns = ['Variance', 'Skewness', 'Curtosis','Entropy','Class']
data.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

# create target and variables

In [5]:
x = data.drop('Class', axis = 1)
y = data['Class']

# Split data

In [6]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte = train_test_split(x,y,test_size=0.3, random_state=0)

# model build and fit

        SVC(
            *,
            C=1.0,
            kernel='rbf',
            degree=3,
            gamma='scale',
            coef0=0.0,
            shrinking=True,
            probability=False,
            tol=0.001,
            cache_size=200,
            class_weight=None,
            verbose=False,
            max_iter=-1,
            decision_function_shape='ovr',
            break_ties=False,
            random_state=None,
        )
* options for kernel:
 * ['linear', 'poly', 'rbf', 'sigmoid', 'precomputed']
 
* C the a regularization parameter

* degree is what you give when kernel is polynomial

In [10]:
from sklearn.svm import SVC
model = SVC(kernel='linear',C=1.0)
model.fit(xtr,ytr)

SVC(kernel='linear')

# predictions

In [11]:
y_pred = model.predict(xte)

# Result and metrics

In [12]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print(classification_report(yte,y_pred))
print(accuracy_score(yte,y_pred))
print(confusion_matrix(yte,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       232
           1       0.97      1.00      0.99       180

    accuracy                           0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412

0.9878640776699029
[[227   5]
 [  0 180]]


# trying more

In [13]:
import numpy as np
randList=[]
for i in [10,20,30,40,50]:
    randList.append(np.random.randint(i))
randList

[6, 2, 24, 33, 25]

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
import numpy as np

#dictionary to keep track of score and to calculate average
scoreDict={'linear':[],'poly':{1:[],2:[],3:[],4:[]},'rbf':[],'sigmoid':[]}


for randNum in randList:
    print("***************Random number: ",randNum,"\n")
    
    #splitting
    X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3,random_state=randNum)
    
    #populate required values for model
    kernelLst=['linear', 'poly', 'rbf', 'sigmoid']
    polyDegree=[1,2,3,4]
    
    for kernel_ in kernelLst:
        if kernel_=='poly':
            for degree_ in polyDegree:
                model=SVC(kernel=kernel_,degree=degree_)
                model.fit(X_train, y_train)
                score=model.score(X_test,y_test)
                print(kernel_,"degree ",degree_," score: ",score)
                print("Confusion Matrix: \n",confusion_matrix(y_test,model.predict(X_test)))
                print("Classification Report: \n",classification_report(y_test,model.predict(X_test)))
                #send the score value to the dictionary
                scoreDict[kernel_][degree_].append(score)
        else:
            model=SVC(kernel=kernel_)
            model.fit(X_train, y_train)
            score=model.score(X_test,y_test)
            print(kernel_," score:  ",score)
            print("Confusion Matrix: \n",confusion_matrix(y_test,model.predict(X_test)))
            print("Classification Report: \n",classification_report(y_test,model.predict(X_test)))
            #send the score value to the dictionary
            scoreDict[kernel_].append(score)
        print("\n\n")
#print(scoreDict)

***************Random number:  6 

linear  score:   0.9927184466019418
Confusion Matrix: 
 [[222   1]
 [  2 187]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99       223
           1       0.99      0.99      0.99       189

    accuracy                           0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412




poly degree  1  score:  0.9951456310679612
Confusion Matrix: 
 [[221   2]
 [  0 189]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      0.99      1.00       223
           1       0.99      1.00      0.99       189

    accuracy                           1.00       412
   macro avg       0.99      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412

poly degree  2  score:  0.9830097087378641
Confusion Matrix: 
 [[216   7]
 [  0 189]]
Classif

rbf  score:   1.0
Confusion Matrix: 
 [[229   0]
 [  0 183]]
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       229
           1       1.00      1.00      1.00       183

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412




sigmoid  score:   0.6893203883495146
Confusion Matrix: 
 [[167  62]
 [ 66 117]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.72      0.73      0.72       229
           1       0.65      0.64      0.65       183

    accuracy                           0.69       412
   macro avg       0.69      0.68      0.68       412
weighted avg       0.69      0.69      0.69       412




***************Random number:  25 

linear  score:   0.9878640776699029
Confusion Matrix: 
 [[222   3]
 [  2 185]]
Classification Report: 
          